name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        with:
          username: fransdroid
          show_icons: true
          include_all_commits: true
          count_private: true
          theme: tokyonight
