name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=fransdroid&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight" > github-stats.png
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github-stats.png
          git commit -m "Updated GitHub Stats"
          git push
